name: todo-workflow
on: push
jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
#      - name: Check out repository code
#        uses: actions/checkout@v4
#      - name: build
#        run: docker build -t jonathan78docker/todo-app .
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
#      - run: docker push jonathan78docker/todo-app
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: jonathan78docker/todo-app:latest
      
